/*
course: CSC189
project: Lab11
date: Nov. 5th, 2021
author: Chris Ball
purpose: A program to play the number guessing game
*/
package lab11;
import java.util.*;
class NumberGuessingGame {
    int secret; //secret number generated by the computer
    
    //constructor to initialize secret by generating a random integer
    //in rage 0~n
    NumberGuessingGame(int n){
        Random rand = new Random();
        secret = rand.nextInt(n+1);
    }
    
    //Reset the secret number
    void resetSecret(int n) {
        Random rand = new Random();
        secret = rand.nextInt(n+1);
    }
    
    void playGame() {
        Scanner guess = new Scanner(System.in);
        int i;
        System.out.println("Guess The Secret Number Between 1 and 999!!");
        for(i=1;i<=10;i++){
            int x = guess.nextInt();
            if(x>secret){
                System.out.println("That number is too high! Try Again.");
            }
            if(x<secret)
                System.out.println("That number is too low! Try Again.");
            if(x==secret){
                System.out.println("Congratulations, you won the game! You got it in "+i+" tries.");
                break;
            }
        }
        if(i>10)
            System.out.println("Sorry, you lost the game! The answer should be "+secret);
    }
}
public class Lab11 {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        String res;
        
        NumberGuessingGame game = new NumberGuessingGame(999);
        
        do{
            System.out.println("1.Play the game");
            System.out.println("2.Exit");
            
            res = in.next();
            switch(res.charAt(0)){
                case '1':
                    game.playGame();
                    game.resetSecret(999);
                    break;
                case '2':
                    System.out.println("Thank you for playing!");
                    break;
                default:
                    System.out.println("Invalid Input!");
            }
        }while(res.charAt(0)!='2');
        
    }
    
}
